[program:gogal-api]
directory=/opt/gogal/current
command=/opt/gogal/current/gogal-server
autostart=true
autorestart=true
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true
user=gogal
environment=GIN_MODE=release
stdout_logfile=/var/log/gogal/api.out.log
stderr_logfile=/var/log/gogal/api.err.log

